### ISSUE TITLE
Import Error when entry_point is different to Github Repo Url

### ISSUE THREAD

**Issue by AmusedNetwork** [controversial/livejson#11]
When adding a module to `pythonista.cloud` with the API, if the Github Repo is named differently to the `entry_point` then an Import Error is displayed. This is because `pythonista.cloud` is looking for the py file with the name of the Repo, not the `entry_point`

For Example:
`from cloud import testPyModule` where testPyModule is the Repo name and the entry point is 
`thisIsATestModule.py`, the import fails.

http://db.pythonista.cloud/testPyModule

```
{
    _id: "testPyModule",
    _rev: "1-abced0386af3f17e7a2a6f25edba12f7",
    name: "testPyModule",
    url: "https://github.com/TheJJ100100/testPyModule",
    entry_point: "thisIsATestModule.py",
    py_versions: [
        2,
        3
    ]
}
```

Error Message: 
<img src="https://cloud.githubusercontent.com/assets/5558617/16632033/18fe4d88-43ba-11e6-9ba9-d4d7ae06fc69.jpeg" width="320" height="680">

**Comment by AmusedNetwork** [comment]
@controversial Tag with [bug]?

**Comment by controversial** [comment]
Please open this issue on [the pythonista.cloud repo](https://github.com/controversial/pythonista.cloud)
